# Ameba configuration for ansi library
Version: "1.7.0-dev"

Excluded:
  - temp/**/*
  - lib/**/*
  - vendor/**/*
  - spec/**/*


Lint/Formatting:
  Excluded:
    - spec/**/*.cr
    - temp/**/*.cr

Lint/NotNil:
  Excluded:
    - spec/**/*.cr

# need to add file to exclude them so we can selectively turn off
# Metrics/CyclomaticComplexity:
# Excluded:
